### ISSUE TITLE
Work with Kelly to use Duke's data

### ISSUE THREAD

**Issue by dlebauer** [terraref/drone-pipeline#11]
@Chris-Schnaufer commented on [Mon Feb 11 2019](https://github.com/danforthcenter/sentinel-detection/issues/14)

* [x] Get David to grant access to Duke's data
* [ ] Process Dukes data to OM
* [ ] Have Kelly review result
* [ ] Begin working on integrating Kelly into workflow

* [ ] Find and integrate plot shape files and clip out plots

---

@dlebauer commented on [Wed Feb 13 2019](https://github.com/danforthcenter/sentinel-detection/issues/14#issuecomment-463376900)

@Chris-Schnaufer this should be in the drone-pipeline repository ...

---

@dlebauer commented on [Tue Feb 19 2019](https://github.com/danforthcenter/sentinel-detection/issues/14#issuecomment-465142263)

should this be an epic?
