### ISSUE TITLE
Fix email issue with clowder

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/drone-pipeline#25]
**Task to do**
Get clowder to send out emails

**Reason**
Registration and other email notifications aren't working

**Result**
Emails work properly

**Steps to take**
- [x] Use the following SMTP server: mailgate.cyverse.org
- [x] Confirm emails are sent from Clowder
- [ ] Confirm emails are sent from extractors

**Comment by Chris-Schnaufer** [comment]
User documentation: https://osf.io/xdkcy/?view_only=a2bf355c63aa471fb8b0a4b60daa320c

Code and README.md(s): https://github.com/terraref/drone-pipeline

Technical OpenStack: https://docs.google.com/document/d/16SoqApyczesGLKcpt0S0_OE7_93-m1EPKLIlhOa3TNE/edit?usp=sharing
