### ISSUE TITLE
Store experiment metadata in the destination dataset

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/drone-pipeline#40]
**Task to do**
Store experiment metadata in the destination dataset

**Reason**
Experiment metadata stored in a dataset can then be subsequently used by other extractors. This is especially helpful when metadata values are not explicitly entered by system users.

**Result**
The metadata used by extractors is stored in relevant datasets

**Steps to take**
- [x] Determine if both the source and destination datasets have the metadata added or updated
- [x] Determine what metadata to store and its hierarchical format
- [x] Add/update metadata when extractors are run
- [x] Extractors make use of stored metadata while allowing experiment.yml files to override stored metadata

**Comment by Chris-Schnaufer** [comment]
Also secured sensitive metadata. This has the added requirement of having a 32-byte key defined for all extractors
