### ISSUE TITLE
Follow drone pipeline tutorial for building custom extractors

### ISSUE THREAD

**Issue by cmbrown89** [terraref/drone-pipeline#56]
Follow this [tutorial](https://github.com/az-digitalag/Drone-Processing-Pipeline/tree/master/extractors-template) and build extractors with different RGB indices that extract greenness from digital images.

Start with using... 

* [x] Excess greeness index = 2g-(r+b)
* [x] percent green = g/(r+b+g)
* [x] Vegetative index = g/(r^a*b^(1-a)); a = 0.667
* [ ] other indices and combined indices
* [ ] Write tests and documentation

Then add other indices and combined indices that are listed in [this](https://docs.google.com/document/d/1cAm5w1Bs6dB1SHgf-HVmwwbebLhbZMUvTkXLtas_-xI/edit) document.

Write tests and documentation

**Comment by dlebauer** [comment]
Convert to an epic and add tickets of smaller scope

**Comment by dlebauer** [comment]
implemented in https://github.com/AgPipeline/transformer-rgb-indices/blob/develop/algorithm_rgb.py
