### ISSUE TITLE
Move extractor template to its own repository

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/drone-pipeline#61]
**Task to do**
Move the extractor template to its own repository

**Reason**
Being in its own repository allows it to become a [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) eliminating the need to perform many actions that can result in lost files and code when setting up a new extractor, or when updating an extractor

**Result**
People can choose to use the repository "as is" or as a submodule.

**Steps to take**
- [x] Place the code in its own repository
- [x] Update the README for a straight clone/checkout/branch
- [x] Update the code and README to support running as a submodule

**Comment by Chris-Schnaufer** [comment]
Repo is here: https://github.com/az-digitalag/dpp-extractor-plot
