### ISSUE TITLE
For image based extractors, replace "identify" binary with a list of acceptable file extensions

### ISSUE THREAD

**Issue by Chris-Schnaufer** [terraref/drone-pipeline#77]
**Task to do**
Replace the use of a binary image type identifier with a simple file name extension check. This will reduce the compute overhead and make code maintenance easier.

**Reason**
Faster, cleaner code

**Result**
Less overhead when running extractors that need to identify image files.

**Extractors**
- [ ] Drone Canopy Cover
- [ ] Plot extractor base container
- [ ] RGBMask in TERRA REF

**Comment by Chris-Schnaufer** [comment]
Closing as obsolete due to move to transformers
